reload-success: "&aSuccessfully reloaded configuration!"
no-permission: "&cYou don't have permission to run this command."

sound:
  enabled: true
  source: "block.note_block.bell"
  volume: 1.0
  pitch: 0.6