name: "AutoReplant"
version: '0.1.0'
main: me.rarehyperion.autoreplant.AutoReplant
api-version: '1.13'
load: STARTUP
authors: [ RareHyperIon ]
description: Automatically replants harvested crops using seeds from your inventory so you can harvest without ever planting again.

commands:
  autoreplant:
    description: "Reload the plugins configuration."
    permission: autoreplant.admin
    usage: /autoreplant reload
    aliases: ["ar"]

permissions:
  autoreplant.admin:
    description: "Allows for reloading the plugins configuration."
    default: op